name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # 🚀 এপিআই কানেকশনের জন্য
  http: ^1.2.1

  # 🎨 ডিজাইন ও ফন্ট
  google_fonts: ^8.0.2
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

  # 🌍 লোকালাইজেশন
  easy_localization: ^3.0.7

  # 🔥 ফায়ারবেস এবং এআই
  firebase_core: ^4.7.0
  firebase_ai: ^3.11.0

  # ⚙️ স্টেট ম্যানেজমেন্ট ও লোকাল স্টোরেজ
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5

  # 📸 ছবি এবং মিডিয়া হ্যান্ডেলিং
  image_picker: ^1.2.1
  image_cropper: ^12.2.1

  # 🕒 সময় ও আইকন
  timeago: ^3.7.1
  phosphor_flutter: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/badge/verified_badge.png
    - assets/reactions/
    - assets/logo/
    - assets/intro/
